# Generated by Django 6.0.4 on 2026-04-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbies_closet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
